--CREATE DATABASE StazioneControlloVoli


CREATE TABLE AEROPORTO(
	[ID_AEROPORTO] [INT] IDENTITY(1,1),
	[Nome] [VARCHAR](30) NOT NULL,
	[Citta] [VARCHAR](30) NOT NULL,
	[Nazione] [VARCHAR](30) NOT NULL,
	[NumeroPiste] [INT] NOT NULL,
	CONSTRAINT PK_AEROPORTO PRIMARY KEY (ID_AEROPORTO),
	CONSTRAINT UQ_AEROPORTO UNIQUE (ID_AEROPORTO, CITTA)
);

CREATE TABLE AEREO(
	[ID_Aereo] [INT] IDENTITY(1,1),
	[TipoAereo] [VARCHAR](20) NOT NULL,
	[NumeroPasseggeri] [INT] NOT NULL,
	[QtaMerci] [INT] NOT NULL,
	CONSTRAINT PK_AEREO PRIMARY KEY (ID_AEREO, TipoAereo)
	--CONSTRAINT UQ_AEREO UNIQUE (ID_AEREO, TipoAereo)
);

CREATE TABLE VOLO(
	[Codice_Volo] [NCHAR](5) NOT NULL,
	[DataVolo] [DATE] NOT NULL,
	[OraPartenza] [TIME] NOT NULL,
	[OraArrivo] [TIME] NOT NULL,
	[ID_AeroportoP] [INT] NOT NULL,
	[CittaP] [VARCHAR](30) NOT NULL,
	[ID_AeroportoA] [int] NOT NULL,
	[CittaA] [VARCHAR](30) NOT NULL,
	CONSTRAINT PK_VOLO PRIMARY KEY (Codice_Volo),
	CONSTRAINT FK_PARTENZA FOREIGN KEY (ID_AeroportoP, CittaP) 
	REFERENCES Aeroporto(ID_Aeroporto, Citta),
	CONSTRAINT FK_ARRIVO FOREIGN KEY (ID_AeroportoA, CittaA)
	REFERENCES Aeroporto (ID_Aeroporto, Citta)
);

