--CREATE DATABASE StazioneControlloVoli


CREATE TABLE AEROPORTO(
	[ID_AEROPORTO] [INT] IDENTITY(1,1),
	[Nome] [VARCHAR](30) NOT NULL,
	[Citta] [VARCHAR](30) NOT NULL,
	[Nazione] [VARCHAR](30) NOT NULL,
	[NumeroPiste] [INT] NOT NULL,
	CONSTRAINT PK_AEROPORTO PRIMARY KEY (ID_AEROPORTO),
	CONSTRAINT UQ_AEROPORTO UNIQUE (ID_AEROPORTO, CITTA)
);

CREATE TABLE AEREO(
	[ID_Aereo] [INT] IDENTITY(1,1),
	[TipoAereo] [VARCHAR](20) NOT NULL,
	[NumeroPasseggeri] [INT] NOT NULL,
	[QtaMerci] [INT] NOT NULL,
	CONSTRAINT PK_AEREO PRIMARY KEY (ID_AEREO, TipoAereo)
	--CONSTRAINT UQ_AEREO UNIQUE (ID_AEREO, TipoAereo)
);

CREATE TABLE VOLO(
	[Codice_Volo] [NCHAR](5) NOT NULL,
	[DataVolo] [DATE] NOT NULL,
	[OraPartenza] [TIME] NOT NULL,
	[OraArrivo] [TIME] NOT NULL,
	[ID_AeroportoP] [INT] NOT NULL,
	[CittaP] [VARCHAR](30) NOT NULL,
	[ID_AeroportoA] [int] NOT NULL,
	[CittaA] [VARCHAR](30) NOT NULL,
	CONSTRAINT PK_VOLO PRIMARY KEY (Codice_Volo),
	CONSTRAINT FK_PARTENZA FOREIGN KEY (ID_AeroportoP, CittaP) 
	REFERENCES Aeroporto(ID_Aeroporto, Citta),
	CONSTRAINT FK_ARRIVO FOREIGN KEY (ID_AeroportoA, CittaA)
	REFERENCES Aeroporto (ID_Aeroporto, Citta)
);


INSERT INTO Aereo (TipoAereo, QtaMerci, NumeroPasseggeri) 
VALUES ('Boeing 757', 250, 200);
INSERT INTO AEREO VALUES ('Aliante X', 20, 130);
INSERT INTO AEREO VALUES ('Boeing 737', 250, 100);
INSERT INTO AEREO VALUES ('Boeing 737', 200, 300);

SELECT *
FROM AEREO
WHERE QtaMerci > 120 OR NumeroPasseggeri = 250 

SELECT * 
FROM AEREO
WHERE QtaMerci > 120
UNION
SELECT *
FROM AEREO
WHERE NumeroPasseggeri = 250

-- Versione STANDARD SQL PER OTTENERE UNA TABELLA A PARTIRE DA UNA QUERY
CREATE TABLE AereiNonDiLinea with(
NumP INT , 
qtamerci INT
) AS
SELECT NumeroPasseggeri, QtaMerci 
FROM AEREO
WHERE NumeroPasseggeri < 100

-- VERSIONE CORRETTA
select *
into aereinondilinea
from aereo
where NumeroPasseggeri < 100

INSERT INTO AEROPORTO VALUES ('Malpensa', 'Milano', 'Italia', 5)
INSERT INTO AEROPORTO VALUES ('Ciampino', 'Roma', 'Italia', 15)
INSERT INTO AEROPORTO VALUES ('De Gaulle', 'Parigi', 'Francia', 25)
INSERT INTO AEROPORTO VALUES ('Kennedy', 'Los Angeles', 'USA', 12)
INSERT INTO AEROPORTO VALUES ('Capodichino', 'Napoli', 'Italia', NULL)

select * from AEROPORTO

ALTER TABLE VOLO
ADD ID_AEREO INT
ALTER TABLE VOLO
ADD TIPO_AEREO VARCHAR(20)

ALTER TABLE VOLO
ADD CONSTRAINT FK_AEREO FOREIGN KEY (ID_AEREO, TIPO_AEREO)
REFERENCES AEREO (ID_AEREO, TIPOAEREO)

INSERT INTO VOLO VALUES ('AC123', '27/07/2021', '12:30', '13:30', 1, 
'Milano', 2, 'Roma', 1, 'Boeing 757');
INSERT INTO VOLO VALUES ('AC124', '28/07/2021', '12:30', '14:30', 1, 
'Milano', 3, 'Parigi', 1, 'Boeing 757');
INSERT INTO VOLO VALUES ('AC125', '30/07/2021', '10:30', '22:30', 2, 
'Roma', 4, 'Los Angeles', 3, 'Boeing 737');
INSERT INTO VOLO VALUES ('AC126', '02/08/2021', '09:30', '22:30', 1, 
'Milano', 4, 'Los Angeles', 3, 'Boeing 737');
INSERT INTO VOLO VALUES ('AC127', '03/08/2021', '09:30', '22:30', 1, 
'Milano', 2, 'Roma', 4, 'Boeing 737');
INSERT INTO VOLO VALUES ('AC128', '03/08/2021', '09:30', '22:30', 3, 
'Parigi', 2, 'Roma', 4, 'Boeing 737');
INSERT INTO VOLO VALUES ('AC129', '31/07/2021', '12:30', '13:30', 5, 
'Napoli', 2, 'Roma', 1, 'Boeing 757');

-- DATA MANIPULATION

SELECT * FROM AEREO

select * from AEROPORTO

UPDATE AEREO SET QtaMerci = 200
WHERE ID_AEREO = 1;

--CITTA' DEGLI AEREOPORTI CON NUMERO DI PISTE INDEFINITO
SELECT CITTA as CittaAeroporto
FROM AEROPORTO as A
WHERE A.NumeroPiste IS NOT NULL

-- Nazioni da cui parte e arriva il volo con codice AC124
SELECT a1.Nazione, a2.Nazione
FROM AEROPORTO AS a1 
JOIN VOLO AS v
ON a1.ID_AEROPORTO = v.ID_AEROPORTOP
JOIN AEROPORTO AS A2
ON V.ID_AEROPORTOA = A2.ID_AEROPORTO
WHERE V.CODICE_VOLO = 'AC124'

SELECT a1.Nazione as 'nazione partenza', a2.Nazione as 'nazione arrivo'
FROM AEROPORTO AS A1, VOLO AS V, AEROPORTO AS A2
WHERE a1.ID_AEROPORTO = v.ID_AeroportoP and 
a2.ID_AEROPORTO = v.ID_AeroportoA and v.Codice_Volo = 'AC124'

SELECT *
FROM AEROPORTO AS a1 
LEFT JOIN VOLO AS v
ON a1.ID_AEROPORTO = v.ID_AEROPORTOP
LEFT JOIN AEROPORTO AS A2
ON V.ID_AEROPORTOA = A2.ID_AEROPORTO

-- Tipo aereo dei voli in partenza da Milano
SELECT distinct V.TIPO_AEREO
FROM Volo as V
WHERE V.CittaP = 'Milano' 

SELECT DISTINCT A.ID_Aereo, A.TipoAereo
FROM Volo as V
JOIN Aereo as A
ON V.ID_AeroportoP = A.ID_AEREO AND V.TIPO_AEREO = A.TIPOAEREO
WHERE V.CITTAP = 'Milano'

SELECT distinct a.TipoAereo, a.NumeroPasseggeri
FROM VOLO AS V
JOIN AEREO AS A
ON V.TIPO_AEREO = A.TipoAereo 
WHERE V.CittaP = 'Milano'

-- città da cui partono voli internazionali
SELECT PARTENZA.Citta as Partenza, ARRIVO.CITTA as Arrivo --V.CittaP, V.CittaA
FROM AEROPORTO AS Partenza
JOIN VOLO AS V
ON V.ID_AEROPORTOP = Partenza.ID_AEROPORTO
JOIN AEROPORTO AS ARRIVO
ON V.ID_AEROPORTOA = ARRIVO.ID_AEROPORTO
WHERE PARTENZA.NAZIONE <> ARRIVO.NAZIONE

--città da cui partono voli diretti a roma ordinati alfabeticamente
SELECT DISTINCT CittaP
FROM VOLO 
WHERE CITTAA = 'Roma'
ORDER BY CittaP DESC

-- recuperare il numero di voli internazionali con partenza da napoli
SELECT Count(*) as 'Voli Internazionali Da Napoli'
FROM Volo as V
JOIN Aeroporto as A
ON V.CittaA = A.Citta
WHERE V.CittaP = 'Napoli' and A.Nazione <> 'Italia'

-- numero voli internazionali in partenza da città italiane
SELECT COUNT(*), CittaP
FROM AEROPORTO as Partenza
JOIN Volo as V
ON Partenza.ID_AEROPORTO = V.ID_AEROPORTOP
JOIN AEROPORTO AS Arrivo
ON V.ID_AEROPORTOA = Arrivo.ID_AEROPORTO
WHERE Partenza.Nazione = 'Italia' AND Arrivo.Nazione <> 'Italia'
GROUP BY V.CittaP

SELECT Count(V.CittaA)--, v.CittaA
FROM AEROPORTO AS Partenza 
JOIN VOLO AS V
ON V.CittaP = Partenza.Citta
JOIN AEROPORTO AS Arrivo
ON V.CITTAA = Arrivo.Citta
WHERE Partenza.Nazione = 'Italia'  and arrivo.Nazione <> 'Italia'
GROUP BY V.CittaP, V.CittaA--, Arrivo.Nazione
--HAVING COUNT(v.CittaP) >= 0 and Arrivo.Nazione <> 'Italia'

SELECT V.CittaP
FROM AEROPORTO AS PARTENZA
JOIN VOLO AS V
ON PARTENZA.ID_AEROPORTO = V.ID_AEROPORTOP
JOIN AEROPORTO AS ARRIVO
ON V.ID_AEROPORTOA = ARRIVO.ID_AEROPORTO
WHERE PARTENZA.NAZIONE = 'Francia' AND ARRIVO.NAZIONE = 'Italia'
GROUP BY V.CittaP
HAVING COUNT(*) > 20

-- voli interni (OPERATORE INSIEMISTICO)
select partenza.Nome, PARTENZA.Citta
FROM VOLO AS V
JOIN AEROPORTO AS PARTENZA
ON V.ID_AEROPORTOP = PARTENZA.ID_AEROPORTO
WHERE PARTENZA.NAZIONE = 'ITALIA'
EXCEPT 
SELECT A1.NOME, A1.Citta
FROM AEROPORTO AS A1
JOIN VOLO AS V1 
ON A1.ID_AEROPORTO = V1.ID_AEROPORTOP
JOIN AEROPORTO AS A2
ON V1.ID_AEROPORTOA = A2.ID_AEROPORTO
WHERE (A1.NAZIONE = 'Italia' AND A2.Nazione <> 'Italia')

--VOLI INTERNI (OPERATORE IN)
SELECT PARTENZA.NOME, PARTENZA.CITTA
FROM VOLO AS V
JOIN AEROPORTO AS PARTENZA
ON V.ID_AEROPORTOP = PARTENZA.ID_AEROPORTO
WHERE PARTENZA.NAZIONE = 'Italia' AND PARTENZA.NOME 
NOT IN
(SELECT A1.NOME
FROM AEROPORTO AS A1
JOIN VOLO AS V
ON A1.ID_AEROPORTO = V.ID_AEROPORTOP
JOIN AEROPORTO AS A2
ON V.ID_AEROPORTOA = A2.ID_AEROPORTO
WHERE A1.NAZIONE = 'Italia' AND A2.Nazione <> 'Italia')

--VOLI INTERNI (CON EXIST)
SELECT PARTENZA.Nome, PARTENZA.Citta
FROM VOLO AS V 
JOIN AEROPORTO AS PARTENZA 
ON V.ID_AEROPORTOP = PARTENZA.ID_AEROPORTO
WHERE PARTENZA.NAZIONE = 'Italia'
and NOT EXISTS
(SELECT *
FROM VOLO AS V1 
JOIN AEROPORTO AS ARRIVO
ON V1.ID_AeroportoA = ARRIVO.ID_AEROPORTO
WHERE v1.CittaP = partenza.citta 
and partenza.NAZIONE = 'Italia' AND ARRIVO.NAZIONE <> 'Italia')

-- con join
SELECT A1.CITTA, A1.NOME
from AEROPORTO AS A1 
JOIN VOLO AS V1
ON A1.ID_AEROPORTO = V1.ID_AEROPORTOP
LEFT JOIN AEROPORTO AS A2
ON (V1.ID_AEROPORTOA = A2.ID_AEROPORTO AND A2.NAZIONE = 'Italia')
WHERE A1.NAZIONE = 'Italia'
GROUP BY A1.CITTA, A1.NOME
HAVING COUNT (A2.NAZIONE) = 1


SELECT V.CittaP
FROM VOLO V
JOIN AEREO A
ON V.ID_AEREO = A.ID_AEREO
WHERE A.NUMEROPASSEGGERI = (SELECT MAX(NUMEROPASSEGGERI) FROM AEREO)
UNION
SELECT V.CittaA
FROM VOLO V
JOIN AEREO A
ON V.ID_AEREO = A.ID_Aereo
WHERE A.NumeroPasseggeri = (SELECT MAX(NumeroPasseggeri) FROM AEREO)


